version: '3'

services:
  mocks:
    build: service-mocks
    ports:
      - "8181:8181"
    environment:
      - DEPLOYMENT_ENVIRONMENT=local

  service:
    build: service
    ports:
    - "8080:8080"
    environment:
      - QUOTE_RANDOM_URL=mocks
