management:
  endpoints:
    web:
      base-path: /private
      exposure:
        include: prometheus
        exclude: metrics
      path-mapping:
        prometheus: metrics

service:
  webclient:
    poolSize: 1500
    connectionRequestTimeoutMs: 100
    connectTimeoutMs: 200
    readTimeoutMs: 1800
    totalRequestTimeout: 1000

  quote-random:
    scheme: http
    host: ${QUOTE_RANDOM_URL:localhost}
    port: ${QUOTE_RANDOM_PORT:9090}
    path: ${QUOTE_RANDOM_PATH:/random/quote}
  #    readinessPath: ${QUOTE_RANDOM_READINESS_PATH:/}

  yoda-speech:
    scheme: http
    host: ${QUOTE_RANDOM_URL:localhost}
    port: ${QUOTE_RANDOM_PORT:9090}
    path: ${QUOTE_RANDOM_PATH:/translate/yoda}
#    readinessPath: ${QUOTE_RANDOM_READINESS_PATH:/}