apiVersion: v1
kind: Namespace
metadata:
  name: webflux-template-test
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: webflux-template-test
spec:
  hard:
    pods: "10"
    limits.memory: 2.5Gi
    requests.cpu: "2"
    requests.memory: 2.5Gi
    requests.storage: "0"
    resourcequotas: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: webflux-template-test
data:
  SPRING_PROFILES_ACTIVE: 'test'
  QUOTE_RANDOM_URL: 'webflux-mocks.webflux-template-test'