apiVersion: v1
kind: Namespace
metadata:
  name: webflux-template-int
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: webflux-template-int
spec:
  hard:
    pods: "10"
    limits.memory: 2Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    requests.storage: "0"
    resourcequotas: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: int-config
  namespace: webflux-template-int
data:
  SPRING_PROFILES_ACTIVE: 'int'