configMapRef:
  deployEnv: dev

service:
  name: webflux-mocks
  port: 8181
  portName: client

replicasCount: 1
image:
  repository: bpstelios10/webflux-mocks:0.4.0
limitsMemory: 512Mi
requestsMemory: 512Mi
requestsCpu: 0
readinessProbe:
  path: /__admin
  port: http
  initialDelaySeconds: 15
  timeoutSeconds: 2
livenessProbe:
  path: /__admin
  port: http
  initialDelaySeconds: 15
  timeoutSeconds: 2
containerPort: 8181
portName: http
portProtocol: TCP
env:
  - name: "EXTRA_JAVA_OPTIONS"
    value: "-Xms256m -Xmx256m"
