configMapRef:
  deployEnv: test

service:
  name: webflux-mocks
  port: 9090
  portName: client

replicasCount: 1
image:
  repository: bpstelios10/webflux-mocks:0.4.0
limitsMemory: 1024Mi
requestsMemory: 1024Mi
requestsCpu: 0
readinessProbe:
  path: /__admin
  port: http
  initialDelaySeconds: 15
  timeoutSeconds: 2
livenessProbe:
  path: /__admin
  port: http
  initialDelaySeconds: 15
  timeoutSeconds: 2
containerPort: 9090
portName: http
portProtocol: TCP
env:
  - name: "DEPLOYMENT_ENVIRONMENT"
    value: "webflux-nft"
  - name: "EXTRA_JAVA_OPTIONS"
    value: "-Xms512m -Xmx512m -XX:MaxGCPauseMillis=200"
  - name: "WIREMOCK_OPTS"
    value: "--port 9090 --container-threads=300 --jetty-acceptor-threads=60 --async-response-enabled=true --async-response-threads=50 --global-response-templating"
