job:
  name: webflux-nft
completions: 1
parallelism: 1
backoffLimit: 0
ttlSecondsAfterFinished: 120
restartPolicy: Never
image:
  repository: bpstelios10/webflux-nft:0.13.0
imagePullPolicy: IfNotPresent
limitsMemory: 768Mi
requestsMemory: 768Mi
requestsCpu: 0
env:
  - name: "GATLING_JAVA_OPTS"
    value: "-DtargetEnvironment=webflux-template-test -DtestDuration=600 -DtestType=defaultSimulation -Djava.net.preferIPv4Stack=true -Xmx256m -Xms256m"
  - name: "SIMULATION"
    value: "framework.templates.springbootwebflux.nft.simulations.ServiceSimulation"

preStopDebugMemoryHook: true